org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

mod_id=aerosounds
mod_name=Aero Sounds
mod_version=1.0.0
mod_group=dev.danzy.aerosounds
mod_authors=danzy
mod_license=MIT

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neoforge_version=21.1.247
neoforge_loader_version_range=[4,)
java_version=21
